name: Issues telegram
on:
  issues:
    types: [opened, closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on PR opened
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created PR:
            Path: ${{ GITHUB_EVENT_NAME}}
            Path: ${{ GITHUB_EVENT_PATH }}
            Ref: ${{ GITHUB_REF }}
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}    